### ISSUE TITLE
Blockly standalone does not load on firefox

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-blockly-standalone#9]
Following the instructions of `README.md`, that is, opening `index.html` in Firefox (57.0.1) on Linux, brings the following error message:
```
File not found

Firefox can't find the file at /tmp/thymio-blockly-standalone/data/thymio_blockly.en.html.

    Check the file name for capitalisation or other typing errors.
    Check to see if the file was moved, renamed or deleted.
```

**Comment by cor3ntin** [comment]
Yeah. The layout gets rewritten when  the package is build. 
I think I will edit the readme. `index.html` is a temporary fix until we get clean i18n support.

**Comment by ypiguet-epfl** [comment]
In index.html, line 9 should be
`window.location.replace("./thymio_blockly/thymio_blockly." + userLang + ".html")
`
instead of
`window.location.replace("./data/thymio_blockly." + userLang + ".html")
`

Also it might be useful to suggest to download dependencies (Blockly itself) with
`git clone --recursive https://github.com/aseba-community/thymio-blockly-standalone.git
`
